# Generated by Django 4.0 on 2024-01-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
